language: r
cache: packages

apt_packages:
  - libudunits2-dev
  - gdal-bin
  - libgdal1-dev

warnings_are_errors: false

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
